export const COLORS = {
    backgroundPrimary: "#FFFFFF",
    bisquePrimary: "#FCECDD",
    bisqueSecondary: "#FFD9B3",
    black: "#000000",
    transperentBlack: "rgba(0,0,0, 0.5)",
    error: "#FF0000",
    brownPrimary: "#733349",
    grey: "#C8C8C8",
    greyBackgorund: "#F5F5F5",
    white: "#ffffff",
    greyText: "#6C6E6C",
    green: "#45F680",
    red: "#F6454E",
    brownSecondary: "#DFCFCF",
};
